removeTrailingWhitespace:
    beforeProcessing: 1
    afterProcessing: 1
noAdditionalIndent:
    frame: 1
modifyLineBreaks:
  textWrapOptions:
    columns: 79
    perCodeBlockBasis: 1
    all: 1
  removeParagraphLineBreaks:
    all:
      except:
        - logicproof
        - subproof
    beforeTextWrap: 1
